// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWvsVcoM3OdVqJVQcx9YeyMJ8ajQg8BE',
    appId: '1:170500034711:web:fac7af21479e10be4399d2',
    messagingSenderId: '170500034711',
    projectId: 'date-game-com',
    authDomain: 'date-game-com.firebaseapp.com',
    storageBucket: 'date-game-com.appspot.com',
    measurementId: 'G-2Z40QXXLY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDol6n8GLn8HT5P4xl22GdC4x8XAdNM8PA',
    appId: '1:170500034711:android:2b4d4fbd64cf0ac34399d2',
    messagingSenderId: '170500034711',
    projectId: 'date-game-com',
    storageBucket: 'date-game-com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvrG6zSBknSVqhQnC62HGz6-47Tw2o-A',
    appId: '1:170500034711:ios:fbf7d0505db83f0f4399d2',
    messagingSenderId: '170500034711',
    projectId: 'date-game-com',
    storageBucket: 'date-game-com.appspot.com',
    iosClientId: '170500034711-b9osip54ken4l62pe2a03gkqi0gsutcp.apps.googleusercontent.com',
    iosBundleId: 'com.dategame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuvrG6zSBknSVqhQnC62HGz6-47Tw2o-A',
    appId: '1:170500034711:ios:e4e2b58193e0b1054399d2',
    messagingSenderId: '170500034711',
    projectId: 'date-game-com',
    storageBucket: 'date-game-com.appspot.com',
    iosClientId: '170500034711-asfb9kh4b1vo4mm5nsskl46tis38c8ek.apps.googleusercontent.com',
    iosBundleId: 'com.dategame.RunnerTests',
  );
}
