include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - await_only_futures
    - directives_ordering
    - implementation_imports
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
