name: date_game
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter:
    sdk: flutter
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  layerlens: ^1.0.13

flutter:
  uses-material-design: true

# https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  remove_alpha_ios: true
  image_path: 'assets/icon/icon.png'
  android: true
  ios: true
  web:
    generate: true
